# Generated by Django 4.2.15 on 2024-08-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zibalpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(blank=True, null=True, verbose_name='created at')),
                ('verifiedAt', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('cardNumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='card number')),
                ('status', models.IntegerField(verbose_name='status')),
                ('amount', models.PositiveBigIntegerField(verbose_name='amount')),
                ('refNumber', models.IntegerField(blank=True, null=True, verbose_name='reference number')),
                ('wage', models.IntegerField(verbose_name='wage')),
                ('result', models.IntegerField(verbose_name='result')),
                ('message', models.CharField(max_length=25, verbose_name='message')),
            ],
            options={
                'verbose_name': 'Zibalpay',
                'verbose_name_plural': 'Zibalpay',
            },
        ),
    ]
