# Generated by Django 4.2.15 on 2024-08-15 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20, unique=True, verbose_name='Coupon Code')),
                ('percent', models.PositiveIntegerField(default=0, verbose_name='percent')),
                ('expiration_date', models.DateTimeField(verbose_name='expiration date')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('price', models.BigIntegerField(default=0, verbose_name='price')),
                ('in_stock', models.BigIntegerField(default=0, verbose_name='available in stock')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='category')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='seller')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Product Picture',
                'verbose_name_plural': 'Product Pictures',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='delivery date')),
                ('post_track_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='post track code')),
                ('total_fee', models.BigIntegerField(blank=True, null=True, verbose_name='total fee')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('is_processed', models.BooleanField(default=False, verbose_name='is processed')),
                ('is_sent', models.BooleanField(default=False, verbose_name='is sent')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='is delivered')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='paid date')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ('-created_date', 'is_processed'),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='amount')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='comment body')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='CouponBuyerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.coupon')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'unique_together': {('coupon_id', 'buyer_id', 'product_id')},
            },
        ),
    ]
