# Generated by Django 4.2.15 on 2024-08-15 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='phone number')),
                ('fname', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('lname', models.CharField(blank=True, max_length=30, null=True, verbose_name='last name')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('balance', models.BigIntegerField(default=0, verbose_name='Balance')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('is_seller', models.BooleanField(default=False, verbose_name='is seller')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='date of joining')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='date of update')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='SellerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='seller/videos/', verbose_name='video')),
                ('id_card', models.ImageField(upload_to='seller/cards/', verbose_name='id card image')),
                ('id_number', models.CharField(max_length=10, unique=True, verbose_name='id card number')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_info', to=settings.AUTH_USER_MODEL, verbose_name='seller')),
            ],
            options={
                'verbose_name': 'sellers info',
                'verbose_name_plural': 'sellers info',
            },
        ),
    ]
