# Generated by Django 4.2.15 on 2024-09-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinfo',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
